version: '3'

services:
  db:
    image: 'postgres:16'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=storj
    container_name: db
    networks:
      - storjnetwork
    ports:
      - "5435:5432"
    volumes:
      - ./db/volumes/data:/var/lib/postgresql/data
      - ./db/sql/:/docker-entrypoint-initdb.d/

  paymentservice:
    build: payment
    container_name: paymentservice
    networks:
      - storjnetwork
    ports:
      - "6789:6789"

networks:
    storjnetwork:
      driver: bridge
