version: '3'

services:
  db:
    image: 'postgres:16'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=storj
    container_name: db
    networks:
      - storjnetwork
    volumes:
      - ./db/volumes/data:/var/lib/postgresql/data
      - ./db/sql/:/docker-entrypoint-initdb.d/

  app:
    build: backend
    container_name: storj
    depends_on:
      - db
    networks:
      - storjnetwork
    ports:
      - "8080:8080"

networks:
    storjnetwork:
      driver: bridge