version: '3'

services:
  db:
    image: 'postgres:16'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=storj
    container_name: db
    networks:
      - storjnetwork
    volumes:
      - ./db/volumes/data:/var/lib/postgresql/data
      - ./db/sql/:/docker-entrypoint-initdb.d/

  paymentservice:
    build: payment
    container_name: paymentservice
    depends_on:
      - app
    networks:
      - storjnetwork
    ports:
      - "6789:6789"

  app:
    build: backend
    container_name: storj
    depends_on:
      - db
    networks:
      - storjnetwork
    ports:
      - "8080:8080"

  angular:
    build: frontend
    container_name: angular
    depends_on:
      - app
    networks:
      - storjnetwork
    ports:
      - "4201:4200"

networks:
    storjnetwork:
      driver: bridge