version: '3'

services:
  db:
    image: 'postgres:16'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=storj
    container_name: db
    ports:
      - "5435:5432"
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/